#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
SERVICE_ENV_FILE="${MERGE_EXECUTOR_SERVICE_ENV_FILE:-.merge-executor.env}"
REGISTER_DOC="https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app"
PERMISSIONS_DOC="https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/choosing-permissions-for-a-github-app"
INSTALL_DOC="https://docs.github.com/en/apps/using-github-apps/installing-your-own-github-app"
KEY_DOC="https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/managing-private-keys-for-github-apps"

refuse() {
  printf '  %sERROR %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

file_metadata() {
  local format_bsd="$1" format_gnu="$2" path="$3" value=""
  value=$(stat -f "$format_bsd" "$path" 2>/dev/null) || value=$(stat -c "$format_gnu" "$path" 2>/dev/null) \
    || refuse "prerequisite-stat-unavailable: cannot inspect $path"
  printf '%s' "$value"
}

mode_of() { file_metadata '%Lp' '%a' "$1"; }
uid_of() { file_metadata '%u' '%u' "$1"; }
size_of() { file_metadata '%z' '%s' "$1"; }

reject_placeholder() {
  local name="$1" value="$2" upper=""
  upper=$(printf '%s' "$value" | tr '[:lower:]' '[:upper:]')
  case "$upper" in
    ""|*CHANGE_ME*|*CHANGEME*|*PLACEHOLDER*|*REPLACE_ME*|*TODO*|*EXAMPLE*|*'<'*|*'>'*)
      refuse "placeholder-value: $name must be an installation value, not a placeholder"
      ;;
  esac
}

validate_name() {
  local name="$1" value="$2"
  reject_placeholder "$name" "$value"
  [[ "$value" =~ ^[A-Za-z_][A-Za-z0-9._-]*$ ]] \
    || refuse "invalid-os-user: $name must be one literal account name"
}

validate_identity_boundary() {
  local peer="" peer_count=0 executor_uid="" peer_uid="" groups=""
  validate_name MERGE_EXECUTOR_OS_USER "$MERGE_EXECUTOR_OS_USER"
  id "$MERGE_EXECUTOR_OS_USER" >/dev/null 2>&1 \
    || refuse "missing-os-user: MERGE_EXECUTOR_OS_USER does not exist yet"
  executor_uid=$(id -u "$MERGE_EXECUTOR_OS_USER")
  groups=$(id -Gn "$MERGE_EXECUTOR_OS_USER")
  case " $groups " in
    *" admin "*|*" sudo "*|*" wheel "*)
      refuse "admin-os-user: MERGE_EXECUTOR_OS_USER must be a non-admin account"
      ;;
  esac
  reject_placeholder MERGE_EXECUTOR_PEER_USERS "$MERGE_EXECUTOR_PEER_USERS"
  [[ "$MERGE_EXECUTOR_PEER_USERS" == *,* ]] \
    || refuse "peer-users-incomplete: declare both API and model-runner OS users"
  local old_ifs="$IFS"
  IFS=','
  for peer in $MERGE_EXECUTOR_PEER_USERS; do
    IFS="$old_ifs"
    validate_name MERGE_EXECUTOR_PEER_USERS "$peer"
    [[ "$peer" != "$MERGE_EXECUTOR_OS_USER" ]] \
      || refuse "same-user-peer: executor and peer account names must differ"
    id "$peer" >/dev/null 2>&1 || refuse "missing-peer-user: declared peer $peer does not exist"
    peer_uid=$(id -u "$peer")
    [[ "$peer_uid" != "$executor_uid" ]] \
      || refuse "same-user-peer: executor and peer accounts resolve to the same uid"
    peer_count=$((peer_count + 1))
    IFS=','
  done
  IFS="$old_ifs"
  [[ "$peer_count" -ge 2 ]] || refuse "peer-users-incomplete: declare both API and model-runner OS users"
}

csv_contains() {
  local list="$1" wanted="$2" item="" old_ifs="$IFS"
  IFS=','
  for item in $list; do
    IFS="$old_ifs"
    [[ "$item" == "$wanted" ]] && return 0
    IFS=','
  done
  IFS="$old_ifs"
  return 1
}

validate_control_plane_values() {
  reject_placeholder MERGE_EXECUTOR_RUNNER_ID "$MERGE_EXECUTOR_RUNNER_ID"
  [[ "$MERGE_EXECUTOR_RUNNER_ID" =~ ^[A-Za-z0-9][A-Za-z0-9._:-]*$ ]] \
    || refuse "invalid-runner-id: MERGE_EXECUTOR_RUNNER_ID contains unsupported characters"
  reject_placeholder MERGE_EXECUTOR_RUNNER_IDS "$MERGE_EXECUTOR_RUNNER_IDS"
  csv_contains "$MERGE_EXECUTOR_RUNNER_IDS" "$MERGE_EXECUTOR_RUNNER_ID" \
    || refuse "runner-not-allowlisted: MERGE_EXECUTOR_RUNNER_IDS must contain MERGE_EXECUTOR_RUNNER_ID"
  reject_placeholder MERGE_EXECUTOR_API_URL "$MERGE_EXECUTOR_API_URL"
  [[ "$MERGE_EXECUTOR_API_URL" =~ ^https?://[A-Za-z0-9.-]+(:[1-9][0-9]{0,4})?$ ]] \
    || refuse "invalid-api-url: use one literal http(s) origin with no path, query, credentials, or shell syntax"
}

validate_public_github_values() {
  local name="" value=""
  for name in MERGE_EXECUTOR_GITHUB_APP_ID MERGE_EXECUTOR_GITHUB_APP_INSTALLATION_ID; do
    value="${!name}"
    reject_placeholder "$name" "$value"
    [[ "$value" =~ ^[1-9][0-9]*$ ]] \
      || refuse "invalid-public-identifier: $name must be a positive decimal identifier"
  done
  reject_placeholder MERGE_EXECUTOR_IDENTITY_LOGIN "$MERGE_EXECUTOR_IDENTITY_LOGIN"
  [[ "$MERGE_EXECUTOR_IDENTITY_LOGIN" =~ ^[A-Za-z0-9][A-Za-z0-9-]*\[bot\]$ ]] \
    || refuse "invalid-app-bot-login: expected the installation App slug followed by [bot]"
}

validate_private_key_metadata() {
  local path="$MERGE_EXECUTOR_GITHUB_APP_PRIVATE_KEY_FILE" expected_uid="" actual_uid="" mode="" size="" directory=""
  reject_placeholder MERGE_EXECUTOR_GITHUB_APP_PRIVATE_KEY_FILE "$path"
  [[ "$path" == /* && "$path" =~ ^/[A-Za-z0-9._/-]+$ ]] \
    || refuse "invalid-key-path: use an absolute literal path without whitespace or shell syntax"
  [[ -f "$path" && ! -L "$path" ]] \
    || refuse "key-not-regular-file: private-key destination is missing, non-regular, or a symlink"
  expected_uid=$(id -u "$MERGE_EXECUTOR_OS_USER")
  actual_uid=$(uid_of "$path")
  [[ "$actual_uid" == "$expected_uid" ]] \
    || refuse "key-owner-mismatch: private key is not owned by MERGE_EXECUTOR_OS_USER"
  mode=$(mode_of "$path")
  [[ "$mode" =~ ^[0-7]{3,4}$ ]] || refuse "key-mode-unreadable: private-key mode is not octal"
  (( (8#${mode} & 8#077) == 0 )) \
    || refuse "key-mode-not-owner-only: private key grants group or world access"
  size=$(size_of "$path")
  [[ "$size" =~ ^[1-9][0-9]*$ ]] || refuse "key-size-invalid: private key is empty"
  (( size <= 65536 )) || refuse "key-size-invalid: private key exceeds 65536 bytes"
  directory=${path%/*}
  [[ -n "$directory" ]] || directory="/"
  while :; do
    mode=$(mode_of "$directory")
    [[ "$mode" =~ ^[0-7]{3,4}$ ]] || refuse "key-directory-mode-unreadable: cannot parse metadata for $directory"
    (( (8#${mode} & 8#022) == 0 )) \
      || refuse "key-directory-writable: $directory is group- or world-writable"
    [[ "$directory" == "/" ]] && break
    directory=${directory%/*}
    [[ -n "$directory" ]] || directory="/"
  done
  printf '  %s✓ verified%s private-key owner, mode, size, and parent-directory metadata (key bytes were not read)\n' \
    "$GREEN" "$RESET"
}

validate_executor_token() {
  local operator_token="" runner_token=""
  reject_placeholder MERGE_EXECUTOR_TOKEN "$MERGE_EXECUTOR_TOKEN"
  [[ "$MERGE_EXECUTOR_TOKEN" =~ ^[A-Za-z0-9._~-]{32,4096}$ ]] \
    || refuse "invalid-executor-token: use at least 32 URL-safe random characters"
  operator_token=$(_existing OPERATOR_TOKEN || true)
  runner_token=$(_existing RUNNER_TOKEN || true)
  reject_placeholder OPERATOR_TOKEN "$operator_token"
  reject_placeholder RUNNER_TOKEN "$runner_token"
  [[ "$MERGE_EXECUTOR_TOKEN" != "$operator_token" ]] \
    || refuse "aliased-executor-token: MERGE_EXECUTOR_TOKEN equals OPERATOR_TOKEN"
  [[ "$MERGE_EXECUTOR_TOKEN" != "$runner_token" ]] \
    || refuse "aliased-executor-token: MERGE_EXECUTOR_TOKEN equals RUNNER_TOKEN"
}

require_mode_0600() {
  local path="$1" mode=""
  mode=$(mode_of "$path")
  [[ "$mode" == "600" || "$mode" == "0600" ]] \
    || refuse "secret-output-mode: $path must be mode 0600, found $mode"
}

write_service_environment() {
  local tmp="" key="" value=""
  [[ "$SERVICE_ENV_FILE" =~ ^\.[A-Za-z0-9._-]+$ && "$SERVICE_ENV_FILE" != "$ENV_FILE" ]] \
    || refuse "service-output-path: MERGE_EXECUTOR_SERVICE_ENV_FILE must be a distinct hidden file in this directory"
  [[ ! -L "$SERVICE_ENV_FILE" ]] || refuse "service-output-symlink: refusing to replace a symlink"
  tmp=$(mktemp "${SERVICE_ENV_FILE}.tmp.XXXXXX")
  for key in \
    MERGE_EXECUTOR_GITHUB_APP_ID \
    MERGE_EXECUTOR_GITHUB_APP_INSTALLATION_ID \
    MERGE_EXECUTOR_GITHUB_APP_PRIVATE_KEY_FILE \
    MERGE_EXECUTOR_OS_USER \
    MERGE_EXECUTOR_PEER_USERS \
    MERGE_EXECUTOR_RUNNER_ID \
    MERGE_EXECUTOR_IDENTITY_LOGIN \
    MERGE_EXECUTOR_API_URL \
    MERGE_EXECUTOR_TOKEN; do
    value="${!key}"
    printf '%s=%s\n' "$key" "$value" >> "$tmp"
  done
  chmod 0600 "$tmp"
  mv "$tmp" "$SERVICE_ENV_FILE"
  require_mode_0600 "$SERVICE_ENV_FILE"
  printf '  %s✓ wrote%s executor-only service input → %s (mode 0600)\n' "$GREEN" "$RESET" "$SERVICE_ENV_FILE"
}

[[ "$ENV_FILE" == ".env" ]] \
  || refuse "env-file-override: this wizard updates the repository .env only"
(( EUID != 0 )) || refuse "root-execution: run the wizard as the repository operator, never as root"
[[ -f package.json && -f packages/merge-executor/package.json ]] \
  || refuse "repository-root: run scripts/setup-merge-executor.sh from the AgentOS repository root"
[[ ! -L "$ENV_FILE" ]] || refuse "env-symlink: refusing to read or replace a symlink"
[[ -f "$ENV_FILE" ]] || refuse "env-missing: run npm run setup:local before this wizard"
require_mode_0600 "$ENV_FILE"
umask 077

banner "AgentOS merge executor setup"

stage "Confirm the isolated identities and API binding"
say "This stage records existing configuration. It does not create users, change groups, or invoke sudo."
say "An administrator must already have created one dedicated non-admin executor account and distinct API and model-runner accounts."
ask MERGE_EXECUTOR_OS_USER "Dedicated merge-executor OS user:"
ask MERGE_EXECUTOR_PEER_USERS "Comma-separated API and model-runner OS users:"
ask MERGE_EXECUTOR_RUNNER_ID "Dedicated merge-executor runner id:"
ask MERGE_EXECUTOR_RUNNER_IDS "API allowlist containing that runner id:"
ask MERGE_EXECUTOR_API_URL "AgentOS API origin:"
validate_identity_boundary
validate_control_plane_values
confirm "Have you verified these are distinct service identities, not aliases?" \
  || refuse "identity-confirmation-declined: no configuration was written"

stage "Register an installation-local private GitHub App"
say "You create and own this App. A public installation cannot use another operator's private App."
open_url "$REGISTER_DOC"
step "Follow the official registration concepts; GitHub's current UI labels may drift from the documentation."
step "Choose a private App installable only on its owning account. Do not request OAuth user authorization."
step "Leave Device Flow disabled. Disable the webhook. With no webhook, subscribe to no events."
confirm "Is the App private with OAuth, Device Flow, webhook, and event subscriptions all disabled?" \
  || refuse "app-posture-confirmation-declined: correct the GitHub App before continuing"

stage "Set the repository permission contract"
open_url "$PERMISSIONS_DOC"
say "Set these repository permissions; everything else remains No access:"
step "Administration: Read-only"
step "Checks: Read-only"
step "Commit statuses: Read-only"
step "Contents: Read and write"
step "Merge queues: Read and write"
step "Metadata: Read-only"
step "Pull requests: Read and write"
step "Workflows: Read and write (needed when an authorized merge changes workflow files)"
confirm "Does the App have exactly this permission set and no event subscriptions?" \
  || refuse "permission-confirmation-declined: no configuration was written"

stage "Install on selected repositories and capture public identifiers"
open_url "$INSTALL_DOC"
step "Install the App on the owning account and choose Only select repositories. Select every repository this executor may merge."
step "Copy the App ID from the App settings. This is a public positive decimal identifier."
ask MERGE_EXECUTOR_GITHUB_APP_ID "GitHub App ID:"
step "Copy the installation ID from the selected-repository installation URL. This is also public."
ask MERGE_EXECUTOR_GITHUB_APP_INSTALLATION_ID "GitHub App installation ID:"
step "Copy the App bot login shown for App-authored activity (the App slug followed by [bot])."
ask MERGE_EXECUTOR_IDENTITY_LOGIN "GitHub App bot login:"
validate_public_github_values
confirm "Does this installation expose only the intended repositories?" \
  || refuse "repository-selection-declined: restrict the App installation before continuing"

stage "Validate key custody, capture the executor token, and write configuration"
open_url "$KEY_DOC"
step "Generate a private key in the GitHub App settings. GitHub downloads the only copy."
step "In a separate administrator terminal, install it at the final absolute path owned by the executor user, mode 0600, below non-writable parent directories."
say "That administrator action is not run by this wizard. Confirm it separately before validation."
confirm "Has an administrator installed the downloaded key at its final owner-only path?" \
  || refuse "administrator-key-install-pending: install the key, then rerun"
ask MERGE_EXECUTOR_GITHUB_APP_PRIVATE_KEY_FILE "Final private-key path (not key bytes):"
validate_private_key_metadata
say "The executor API token is separate from the operator token, runner token, App key, and minted GitHub installation token."
ask_secret MERGE_EXECUTOR_TOKEN "Paste the executor-only API token (hidden):"
validate_executor_token

write_env MERGE_EXECUTOR_RUNNER_IDS "$MERGE_EXECUTOR_RUNNER_IDS"
write_env MERGE_EXECUTOR_GITHUB_APP_ID "$MERGE_EXECUTOR_GITHUB_APP_ID"
write_env MERGE_EXECUTOR_GITHUB_APP_INSTALLATION_ID "$MERGE_EXECUTOR_GITHUB_APP_INSTALLATION_ID"
write_env MERGE_EXECUTOR_GITHUB_APP_PRIVATE_KEY_FILE "$MERGE_EXECUTOR_GITHUB_APP_PRIVATE_KEY_FILE"
write_env MERGE_EXECUTOR_OS_USER "$MERGE_EXECUTOR_OS_USER"
write_env MERGE_EXECUTOR_PEER_USERS "$MERGE_EXECUTOR_PEER_USERS"
write_env MERGE_EXECUTOR_RUNNER_ID "$MERGE_EXECUTOR_RUNNER_ID"
write_env MERGE_EXECUTOR_IDENTITY_LOGIN "$MERGE_EXECUTOR_IDENTITY_LOGIN"
write_env MERGE_EXECUTOR_API_URL "$MERGE_EXECUTOR_API_URL"
write_env MERGE_EXECUTOR_TOKEN "$MERGE_EXECUTOR_TOKEN"
require_mode_0600 "$ENV_FILE"
write_service_environment

say "No service was installed, no administrator command was run, and no GitHub request was made by this wizard."
confirm "Do you understand that a separately confirmed administrator must still adopt the runtime and service profile?" \
  || refuse "administrator-adoption-not-confirmed: configuration is written, but no service is installed"

finish
printf '  Next commands (run from this repository):\n'
printf '    npm run build\n'
printf '    sed -n "/^## Service installation/,/^## Post-install verification/p" docs/runbooks/merge-executor.md\n'
printf '  Then run exactly the matching macOS or Linux administrator block shown there.\n'
printf '  Service input to install: %s (mode 0600; contains a secret).\n\n' "$SERVICE_ENV_FILE"
